
print('\n\n\nProblem Two\n\nEach new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.')

answer = 0
a = 0 # previous previous number
b = 1 # previous number
c = a + b # 'this' number

limit = 4000000

while True:
	c = a + b # 'this' number
	a = b
	b = c
	if c > limit:
		break;
	# print(str(c))
	if(c % 2 == 0):
		answer += c



print ('\nFinal Answer: ' + str(answer))

